/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as TechnologiesRouteImport } from './routes/technologies'
import { Route as ApiDownloadProjectRouteImport } from './routes/api/download-project'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsPoliticalRouteImport } from './routes/products.political'
import { Route as ProductsSocioRouteImport } from './routes/products.socio'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologiesRoute = TechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadProjectRoute = ApiDownloadProjectRouteImport.update({
  id: '/api/download-project',
  path: '/api/download-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsPoliticalRoute = ProductsPoliticalRouteImport.update({
  id: '/political',
  path: '/political',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSocioRoute = ProductsSocioRouteImport.update({
  id: '/socio',
  path: '/socio',
  getParentRoute: () => ProductsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/technologies': typeof TechnologiesRoute
  '/api/download-project': typeof ApiDownloadProjectRoute
  '/products/political': typeof ProductsPoliticalRoute
  '/products/socio': typeof ProductsSocioRoute
  '/products/': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/technologies': typeof TechnologiesRoute
  '/api/download-project': typeof ApiDownloadProjectRoute
  '/products/political': typeof ProductsPoliticalRoute
  '/products/socio': typeof ProductsSocioRoute
  '/products': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/technologies': typeof TechnologiesRoute
  '/api/download-project': typeof ApiDownloadProjectRoute
  '/products/political': typeof ProductsPoliticalRoute
  '/products/socio': typeof ProductsSocioRoute
  '/products/': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/download'
    | '/login'
    | '/news'
    | '/privacy'
    | '/products'
    | '/technologies'
    | '/api/download-project'
    | '/products/political'
    | '/products/socio'
    | '/products/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/download'
    | '/login'
    | '/news'
    | '/privacy'
    | '/technologies'
    | '/api/download-project'
    | '/products/political'
    | '/products/socio'
    | '/products'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/download'
    | '/login'
    | '/news'
    | '/privacy'
    | '/products'
    | '/technologies'
    | '/api/download-project'
    | '/products/political'
    | '/products/socio'
    | '/products/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  TechnologiesRoute: typeof TechnologiesRoute
  ApiDownloadProjectRoute: typeof ApiDownloadProjectRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technologies': {
      id: '/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof TechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-project': {
      id: '/api/download-project'
      path: '/api/download-project'
      fullPath: '/api/download-project'
      preLoaderRoute: typeof ApiDownloadProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/political': {
      id: '/products/political'
      path: '/political'
      fullPath: '/products/political'
      preLoaderRoute: typeof ProductsPoliticalRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/socio': {
      id: '/products/socio'
      path: '/socio'
      fullPath: '/products/socio'
      preLoaderRoute: typeof ProductsSocioRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsPoliticalRoute: typeof ProductsPoliticalRoute
  ProductsSocioRoute: typeof ProductsSocioRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsPoliticalRoute: ProductsPoliticalRoute,
  ProductsSocioRoute: ProductsSocioRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  TechnologiesRoute: TechnologiesRoute,
  ApiDownloadProjectRoute: ApiDownloadProjectRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
